const DESTINOS_SEED = [
  {
    id: 1,
    nombre: "Caño Cristales",
    region: "La Macarena, Meta",
    descripcion: "Conocido como 'el río de los cinco colores', sus aguas cristalinas se tiñen de rojo, amarillo, verde, azul y negro gracias a una planta acuática endémica. Un fenómeno natural único en el mundo.",
    precio: 850000,
    duracion: "3 días / 2 noches",
    categoria: "Naturaleza",
    tipoViaje: "Parche individual",
    cupos: 15,
    imagen: "https://media.istockphoto.com/id/1201458044/photo/colombia-cano-cristales-national-park-serrania-de-la-macarena.jpg?s=1024x1024&w=is&k=20&c=b6Ww7Dw7hUYNIwxE6aDn67kWv2Sy2_9jLCbyRXInVyk=",
  },
  {
    id: 2,
    nombre: "Ciudad Amurallada",
    region: "Cartagena, Bolívar",
    descripcion: "Centro histórico declarado Patrimonio de la Humanidad por la UNESCO. Calles coloniales, balcones floridos, murallas frente al mar Caribe y una vibrante vida cultural hacen de este destino una joya imperdible.",
    precio: 420000,
    duracion: "2 días / 1 noche",
    categoria: "Cultural",
    tipoViaje: "Parchemos con amigos",
    cupos: 30,
    imagen: "https://mlqfmr3rpryd.i.optimole.com/cb:0cAX.b2f4/w:auto/h:auto/q:mauto/g:sm/f:best/https://cartagena-tours.co/wp-content/uploads/2023/12/49806996192_ec0e5e29b1_b.jpg",
  },
  {
    id: 3,
    nombre: "Valle de Cocora",
    region: "Salento, Quindío",
    descripcion: "Hogar de la palma de cera, árbol nacional de Colombia y la palmera más alta del mundo. Rodeado de montañas verdes y niebla, es ideal para senderismo en pleno corazón del Eje Cafetero.",
    precio: 280000,
    duracion: "1 día (full day)",
    categoria: "Montaña",
    tipoViaje: "A viajar en familia",
    cupos: 25,
    imagen: "https://images.pexels.com/photos/13829249/pexels-photo-13829249.jpeg",
  },
  {
    id: 4,
    nombre: "Parque Tayrona",
    region: "Santa Marta, Magdalena",
    descripcion: "Playas de arena blanca enmarcadas por la selva tropical y la Sierra Nevada. Caminatas ecológicas, aguas turquesas y biodiversidad excepcional en uno de los parques naturales más visitados del país.",
    precio: 390000,
    duracion: "3 días / 2 noches",
    categoria: "Playa",
    tipoViaje: "Parchemos con amigos",
    cupos: 20,
    imagen: "https://phantom-elmundo.unidadeditorial.es/38a56cccc9ad25c7bf05c58e97acf27c/crop/0x0/2873x1915/resize/646/f/webp/assets/multimedia/imagenes/2024/04/08/17125820913517.jpg",
  },
  {
    id: 5,
    nombre: "Guatapé",
    region: "Guatapé, Antioquia",
    descripcion: "Pueblo de casas coloridas con zócalos pintados a mano, junto al embalse de Guatapé. Subida a la Piedra del Peñol con vistas panorámicas y paseos en lancha por el lago.",
    precio: 310000,
    duracion: "2 días / 1 noche",
    categoria: "Rural",
    tipoViaje: "A viajar en familia",
    cupos: 22,
    imagen: "https://images.pexels.com/photos/4016193/pexels-photo-4016193.jpeg",
  },
  {
    id: 6,
    nombre: "Desierto de la Tatacoa",
    region: "Villavieja, Huila",
    descripcion: "La segunda zona árida más extensa de Colombia. Un paisaje fascinante de formaciones de tierra rojiza y gris, ideal para el senderismo y la observación astronómica gracias a su cielo despejado.",
    precio: 340000,
    duracion: "2 días / 1 noche",
    categoria: "Naturaleza",
    tipoViaje: "Parche individual",
    cupos: 18,
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/34/1c/b2/desierto-de-la-tatacoa.jpg?w=700&h=400&s=1",
  },
  {
    id: 7,
    nombre: "Santuario de Las Lajas",
    region: "Ipiales, Nariño",
    descripcion: "Impresionante iglesia de estilo neogótico construida sobre el cañón del río Guáitara. Considerada una de las maravillas arquitectónicas del mundo por su imponente estructura y entorno natural.",
    precio: 450000,
    duracion: "2 días / 1 noche",
    categoria: "Cultural",
    tipoViaje: "A viajar en familia",
    cupos: 25,
    imagen: "https://images.pexels.com/photos/13783816/pexels-photo-13783816.jpeg",
  },
  {
    id: 8,
    nombre: "Catedral de Sal",
    region: "Zipaquirá, Cundinamarca",
    descripcion: "Una joya arquitectónica subterránea tallada completamente en roca de sal a 180 metros bajo tierra. Un lugar único que combina ingeniería, fe y arte en una antigua mina minera.",
    precio: 150000,
    duracion: "1 día (full day)",
    categoria: "Cultural",
    tipoViaje: "Parche individual",
    cupos: 40,
    imagen: "https://images.pexels.com/photos/36209536/pexels-photo-36209536.jpeg",
  },
  {
    id: 9,
    nombre: "San Andrés Islas",
    region: "San Andrés, Archipiélago",
    descripcion: "Famosa por su 'mar de los siete colores' que degrada desde el azul marino hasta el verde turquesa. Destino caribeño perfecto para el buceo, snorkel, playas de arena coralina y descanso total.",
    precio: 950000,
    duracion: "4 días / 3 noches",
    categoria: "Playa",
    tipoViaje: "Parchemos con amigos",
    cupos: 12,
    imagen: "https://images.pexels.com/photos/3417784/pexels-photo-3417784.jpeg",
  },
  {
    id: 10,
    nombre: "Nevado del Ruiz",
    region: "Manizales, Caldas",
    descripcion: "Aventura de alta montaña en el Parque Nacional Natural Los Nevados. Un recorrido entre paisajes de páramo, vegetación de frailejones y vistas imponentes a las cumbres blancas de la cordillera central.",
    precio: 320000,
    duracion: "1 día (full day)",
    categoria: "Montaña",
    tipoViaje: "Parchemos con amigos",
    cupos: 15,
    imagen: "https://images.pexels.com/photos/17370933/pexels-photo-17370933.jpeg",
  },
  {
    id: 11,
    nombre: "Monserrate y La Candelaria",
    region: "Bogotá, Cundinamarca",
    descripcion: "Sube en teleférico o funicular hasta el cerro de Monserrate para ver la capital a tus pies, y recorre después las calles empedradas y coloridas de La Candelaria, el corazón histórico de Bogotá.",
    precio: 200000,
    duracion: "1 día (full day)",
    categoria: "Cultural",
    tipoViaje: "Parche individual",
    cupos: 35,
    imagen: "https://images.pexels.com/photos/19676274/pexels-photo-19676274.jpeg",
  },
  {
    id: 12,
    nombre: "Comuna 13",
    region: "Medellín, Antioquia",
    descripcion: "De barrio marcado por el conflicto a símbolo de transformación social a través del arte. Sus escaleras eléctricas, grafitis gigantes y hip hop callejero cuentan la historia de resiliencia de Medellín.",
    precio: 180000,
    duracion: "1 día (full day)",
    categoria: "Cultural",
    tipoViaje: "Parchemos con amigos",
    cupos: 28,
    imagen: "https://images.pexels.com/photos/37278658/pexels-photo-37278658.jpeg",
  },
  {
    id: 13,
    nombre: "Villa de Leyva",
    region: "Villa de Leyva, Boyacá",
    descripcion: "Uno de los pueblos coloniales mejor conservados de Colombia, con la plaza principal empedrada más grande del país. Fósiles marinos, viñedos y paisajes de montaña a pocas horas de Bogotá.",
    precio: 260000,
    duracion: "2 días / 1 noche",
    categoria: "Rural",
    tipoViaje: "A viajar en familia",
    cupos: 24,
    imagen: "https://images.pexels.com/photos/17413264/pexels-photo-17413264.jpeg",
  },
  {
    id: 14,
    nombre: "Barichara",
    region: "Barichara, Santander",
    descripcion: "Considerado uno de los pueblos más bonitos de Colombia. Calles de piedra, fachadas blancas y techos de teja, rodeado del cañón del río Suárez. Ideal para caminar el Camino Real hasta Guane.",
    precio: 300000,
    duracion: "2 días / 1 noche",
    categoria: "Rural",
    tipoViaje: "Parche individual",
    cupos: 20,
    imagen: "https://images.pexels.com/photos/31649387/pexels-photo-31649387.jpeg",
  },
  {
    id: 15,
    nombre: "Santa Cruz de Mompox",
    region: "Mompox, Bolívar",
    descripcion: "Ciudad colonial a orillas del río Magdalena, Patrimonio de la Humanidad, famosa por su filigrana de oro y plata, sus balcones republicanos y un ambiente detenido en el tiempo.",
    precio: 380000,
    duracion: "3 días / 2 noches",
    categoria: "Cultural",
    tipoViaje: "A viajar en familia",
    cupos: 18,
    imagen: "https://www.tomplanmytrip.com/wp-content/uploads/2024/06/Main-Square-Santa-Cruz-de-Mompox-East-Caribbean-Coast-1.jpg",
  },
  {
    id: 16,
    nombre: "Providencia",
    region: "Providencia, Archipiélago de San Andrés",
    descripcion: "Hermana pequeña de San Andrés, más tranquila y menos turística. Snorkel en la Barrera de Coral, Old Providence, y el famoso Hoyo Soplador. Naturaleza caribeña casi intacta.",
    precio: 1100000,
    duracion: "4 días / 3 noches",
    categoria: "Playa",
    tipoViaje: "Parchemos con amigos",
    cupos: 14,
    imagen: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/1d/a3/c0/el-lugar-es-hermoso-100.jpg?w=1400&h=-1&s=1",
  },
  {
    id: 17,
    nombre: "Cabo de la Vela",
    region: "La Guajira",
    descripcion: "Territorio ancestral wayúu entre el desierto y el mar Caribe. Kitesurf, atardeceres en el Pilón de Azúcar y una experiencia cultural profunda en una de las regiones más auténticas de Colombia.",
    precio: 420000,
    duracion: "3 días / 2 noches",
    categoria: "Aventura",
    tipoViaje: "Parche individual",
    cupos: 16,
    imagen: "https://images.pexels.com/photos/13209625/pexels-photo-13209625.jpeg",
  },
  {
    id: 18,
    nombre: "Ciudad Perdida",
    region: "Sierra Nevada de Santa Marta, Magdalena",
    descripcion: "Trekking de varios días por la selva hasta las ruinas de Teyuna, una ciudad indígena precolombina anterior a Machu Picchu. Ríos, cascadas y comunidades ancestrales en el camino.",
    precio: 980000,
    duracion: "4 días / 3 noches",
    categoria: "Aventura",
    tipoViaje: "Parchemos con amigos",
    cupos: 12,
    imagen: "https://turcol.co/wp-content/uploads/2020/12/Lost-city-trek-2.png",
  },
  {
    id: 19,
    nombre: "Popayán",
    region: "Popayán, Cauca",
    descripcion: "La 'Ciudad Blanca', con uno de los centros históricos coloniales mejor conservados de Latinoamérica. Cuna de la gastronomía payanesa y escenario de una de las procesiones de Semana Santa más importantes del mundo.",
    precio: 240000,
    duracion: "2 días / 1 noche",
    categoria: "Cultural",
    tipoViaje: "A viajar en familia",
    cupos: 26,
    imagen: "https://images.pexels.com/photos/13200191/pexels-photo-13200191.jpeg",
  },
  {
    id: 20,
    nombre: "Leticia y el Amazonas",
    region: "Leticia, Amazonas",
    descripcion: "Puerta de entrada a la selva amazónica colombiana. Navega por el río Amazonas, visita comunidades indígenas y explora una de las reservas de biodiversidad más grandes del planeta.",
    precio: 1250000,
    duracion: "4 días / 3 noches",
    categoria: "Naturaleza",
    tipoViaje: "Parche individual",
    cupos: 10,
    imagen: "https://images.pexels.com/photos/17025853/pexels-photo-17025853.jpeg",
  },
];

function inicializarSeed() {
  const datosExistentes = localStorage.getItem("destinos");
  const destinos = datosExistentes ? JSON.parse(datosExistentes) : [];
  const necesitaMigracion =
    destinos.length !== DESTINOS_SEED.length ||
    destinos.some((d) => !d.tipoViaje || !d.imagen || !d.imagen.startsWith("http"));

  if (!datosExistentes || necesitaMigracion) {
    localStorage.setItem("destinos", JSON.stringify(DESTINOS_SEED));
    console.log(`✅ Seed cargado con ${DESTINOS_SEED.length} destinos de Colombia.`);
  }
}

inicializarSeed();